server:
  port: 8082

spring:
  application:
    name: university-service
  data:
    rest:
      detection-strategy: annotated
  config:
    import:
      - optional:configserver:http://${CONFIG_SERVER_HOST:config-server}:8888

  kafka:
    producer:
      bootstrap-servers: apache-kafka:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

vault:
  db_url: jdbc:postgresql://localhost:5432/lmsdb
  db_username: lmsdb_user
  db_password: lmsdb123
  cognito_issuer_uri: https://accounts.google.com
  cognito_client_id: local-client-id
  cognito_client_secret: local-client-secret
  cognito_client_name: Local Cognito Client
  cognito_domain: https://example.com
  aws_region: us-east-1
  aws_access_key: local-access-key
  aws_secret_key: local-secret-key
  cognito_user_pool_id: us-east-1_example

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  default-consumes-media-type: application/json
